#!/usr/bin/env python3
"""
Generate examples.rst from examples.toml + the .py source files.

The examples.toml manifest and the .py files in bindings/python/examples/ are the single
source of truth. This script reads both (via examples._registry) and produces structured
RST documentation.

Usage:
    python generate_examples_doc.py --update   # Write examples.rst
    python generate_examples_doc.py --dry-run  # Preview without writing
    python generate_examples_doc.py --check    # Fail if examples.rst is stale
"""

import argparse
import sys
from pathlib import Path
from typing import Any

# Importable because bindings/python/ is the project root; see [tool.mypy] mypy_path and
# [tool.pytest.ini_options] pythonpath in pyproject.toml.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from examples._registry import (  # noqa: E402
    CATEGORY_ORDER,
    EXAMPLES_CATALOG,
    get_category_info,
    get_examples_by_category,
)

GITHUB_BASE = "https://github.com/rudof-project/rudof/blob/master/bindings/python/examples"


# ---------------------------------------------------------------------------
# RST helpers
# ---------------------------------------------------------------------------

def _code_block(code: str) -> list[str]:
    """Format Python code as an RST code-block."""
    lines = [".. code-block:: python", ""]
    for line in code.rstrip("\n").split("\n"):
        lines.append(f"    {line}" if line.strip() else "")
    lines.append("")
    return lines


def _file_links(files: dict[str, Any]) -> list[str]:
    """Format referenced files as RST links."""
    lines = []
    for file_type, file_path in files.items():
        if file_path is None:
            continue
        url = f"{GITHUB_BASE}/{file_path}"
        lines.append(f"- **{file_type.capitalize()}**: `{file_path} <{url}>`_")
    return lines


# ---------------------------------------------------------------------------
# Per-example and per-category RST generation
# ---------------------------------------------------------------------------

def _example_entry(example_id: str, data: dict[str, Any]) -> list[str]:
    """Generate RST for one example."""
    lines = []

    title = data.get("title", example_id.replace("_", " ").title())
    lines.append(title)
    lines.append("^" * len(title))
    lines.append("")
    lines.append(data["description"])
    lines.append("")

    source = data.get("source_file", "")
    if source:
        lines.append(f"**Source**: `{source} <{GITHUB_BASE}/{source}>`_")
        lines.append("")

    lines.append("**Python code:**")
    lines.append("")
    lines.extend(_code_block(data["code"]))

    files = data.get("files", {})
    if files:
        lines.append("**Referenced files:**")
        lines.append("")
        lines.extend(_file_links(files))
        lines.append("")

    lines.append("")
    return lines


def _category_section(category: str) -> list[str]:
    """Generate RST for one category (heading + all its examples)."""
    info = get_category_info(category)
    examples = get_examples_by_category(category)
    if not examples:
        return []

    title = info["title"]
    lines = [title, "-" * len(title), ""]
    for desc_line in info["description"].strip().splitlines():
        lines.append(desc_line)
    lines += ["", ""]

    for eid, edata in examples.items():
        lines.extend(_example_entry(eid, dict(edata)))

    return lines


# ---------------------------------------------------------------------------
# Full document
# ---------------------------------------------------------------------------

def generate_full_examples_rst() -> str:
    """Return the complete examples.rst content."""
    lines = [
        ".. This file is GENERATED by docs/generate_examples_doc.py — do not edit it.",
        "   Edit examples/examples.toml or the example sources, then run:",
        "       python docs/generate_examples_doc.py --update",
        "",
        "Examples",
        "=" * 8,
        "",
        "Validated Python examples demonstrating pyrudof. Every example on this page is run",
        "by the test suite and its output checked, so the code here is known to work against",
        "this version of the library.",
        "",
        "",
    ]

    for cat in CATEGORY_ORDER:
        lines.extend(_category_section(cat))

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI actions
# ---------------------------------------------------------------------------

_RST_FILE = Path(__file__).resolve().parent / "examples.rst"


def _stats(content: str) -> str:
    return (
        f"  - Total lines: {len(content.splitlines())}\n"
        f"  - Examples: {len(EXAMPLES_CATALOG)}\n"
        f"  - Categories: {len(CATEGORY_ORDER)}"
    )


def cmd_update() -> None:
    content = generate_full_examples_rst()
    _RST_FILE.write_text(content, encoding="utf-8")
    print(f"Generated {_RST_FILE.name}\n{_stats(content)}")


def cmd_dry_run() -> None:
    content = generate_full_examples_rst()
    print("=" * 60)
    print("DRY RUN - preview of examples.rst")
    print("=" * 60)
    print(content[:3000])
    if len(content) > 3000:
        print("\n... (truncated) ...\n")
    print("=" * 60)
    print(_stats(content))


def cmd_check() -> None:
    """Exit non-zero if examples.rst is stale (useful in CI)."""
    if not _RST_FILE.exists():
        print(f"FAIL: {_RST_FILE.name} does not exist. Run with --update.")
        sys.exit(1)

    expected = generate_full_examples_rst()
    actual = _RST_FILE.read_text(encoding="utf-8")

    if actual.rstrip("\n") == expected.rstrip("\n"):
        print(f"OK: {_RST_FILE.name} is up to date.")
        sys.exit(0)

    print(
        f"FAIL: {_RST_FILE.name} is stale. "
        f"Run `python {Path(__file__).name} --update` to regenerate."
    )
    sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate examples.rst from examples.toml + the .py files"
    )
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    parser.add_argument("--update", action="store_true", help="Write examples.rst")
    parser.add_argument(
        "--check", action="store_true", help="Fail if examples.rst is stale (for CI)"
    )

    args = parser.parse_args()

    if args.check:
        cmd_check()
    elif args.dry_run:
        cmd_dry_run()
    elif args.update:
        cmd_update()
    else:
        parser.print_help()
        print("\nUse --update to generate, --dry-run to preview, or --check for CI.")


if __name__ == "__main__":
    main()
