# Configuration for testing parallel writing
# This configuration enables parallel writing to multiple files

[generation]
entity_count = 100                    # Generate 100 entities for testing
seed = 12345                         # Use fixed seed for reproducible results
entity_distribution = "Equal"        # Distribute entities equally across shapes
cardinality_strategy = "Balanced"    # Use balanced cardinality strategy

[field_generators.default]
locale = "en"                        # Generate English text
quality = "Medium"                   # Medium quality data

# Configure specific data types
[field_generators.datatypes."http://www.w3.org/2001/XMLSchema#integer"]
generator = "integer"
[field_generators.datatypes."http://www.w3.org/2001/XMLSchema#integer".parameters]
min = 1
max = 10000

[field_generators.datatypes."http://www.w3.org/2001/XMLSchema#decimal"]
generator = "decimal"
[field_generators.datatypes."http://www.w3.org/2001/XMLSchema#decimal".parameters]
min = 0.0
max = 1000.0
precision = 2

[field_generators.datatypes."http://www.w3.org/2001/XMLSchema#date"]
generator = "date"
[field_generators.datatypes."http://www.w3.org/2001/XMLSchema#date".parameters]
start_year = 1980
end_year = 2024

# Configure specific properties
[field_generators.properties."http://example.org/name"]
generator = "string"
parameters = {}

[field_generators.properties."http://example.org/legalName"]
generator = "string"
parameters = {}

[output]
path = "parallel_output.ttl"         # Base output file name
format = "Turtle"                    # Use Turtle format
compress = false                     # Don't compress output
write_stats = true                   # Include generation statistics
parallel_writing = true             # Enable parallel writing
parallel_file_count = 4             # Write to 4 parallel files

[parallel]
worker_threads = 4                   # Use 4 parallel threads
batch_size = 25                     # Entity batch size
parallel_shapes = true              # Process shapes in parallel
parallel_fields = true              # Generate fields in parallel
