version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3"
    rust: "1.87"
  apt_packages:
    - clang

python:
  install:
    - requirements: python/requirements.dev.txt
    - method: pip
      path: python

submodules:
  include: all