version: 2

sphinx:
  builder: html
  configuration: bindings/python/docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    rust: "latest"
  apt_packages:
    - clang
    - libssl-dev
    - pkg-config

python:
  install:
    - method: pip
      path: bindings/python
      extra_requirements:
        - docs

submodules:
  include: all
