mod base;
mod compare;
mod completion;
mod config;
mod convert;
mod data;
mod dctap;
mod generate;
mod materialize;
mod mcp;
mod node;
mod pgschema;
mod pgschema_validate;
mod query;
mod rdf_config;
mod service;
mod shacl;
mod shacl_validate;
mod shapemap;
mod shex;
mod shex_validate;
mod sparql;
mod validate;

pub(crate) use base::extract_common;
pub use base::{Command, CommandContext, CommandFactory};
pub use compare::CompareCommand;
pub use completion::CompletionCommand;
pub use config::ConfigCommand;
pub use convert::ConvertCommand;
pub use data::DataCommand;
pub use dctap::DctapCommand;
pub use generate::GenerateCommand;
pub use materialize::MaterializeCommand;
pub use mcp::McpCommand;
pub use node::NodeCommand;
pub use pgschema::PgschemaCommand;
pub use pgschema_validate::PgschemaValidateCommand;
pub use query::QueryCommand;
pub use rdf_config::RdfConfigCommand;
pub use service::ServiceCommand;
pub use shacl::ShaclCommand;
pub use shacl_validate::ShaclValidateCommand;
pub use shapemap::ShapemapCommand;
pub use shex::ShexCommand;
pub use shex_validate::ShexValidateCommand;
pub use sparql::SparqlCommand;
pub use validate::ValidateCommand;
