[package]
name = "shex_compact_winnow"
version = "0.0.11"

[dependencies]
shex_ast = { workspace = true }
iri_s = { workspace = true }
srdf = { workspace = true }
prefixmap = { workspace = true }
shapemap = { workspace = true }
thiserror = "2"
colored = "3"
rust_decimal = "1.32"
pretty = "0.12.3"

[dev-dependencies]
criterion = "0.5"
pprof = { version = "0.13.0", features = ["criterion", "flamegraph"] }

