# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import os
import pathlib
import typing
__all__ = [
    "ArcDirection",
    "CardinalityStrategy",
    "ComparisonError",
    "ConfigError",
    "ConversionError",
    "ConversionFormat",
    "ConversionMode",
    "DCTapError",
    "DCTapFormat",
    "DataError",
    "DataGenerator",
    "DataQuality",
    "DbEngine",
    "DdlDialect",
    "EntityDistribution",
    "GenerateError",
    "GeneratorConfig",
    "InputError",
    "InternalError",
    "IriError",
    "MapStateError",
    "MaterializeError",
    "NeighborArc",
    "NeighborArcIterator",
    "NodeInspectionError",
    "OutputFormat",
    "PgDbError",
    "PgSchemaError",
    "PgSchemaFormat",
    "PgSchemaValidationEntry",
    "PgSchemaValidationEntryIterator",
    "PgSchemaValidationReport",
    "PrefixesError",
    "QueryError",
    "QueryResultFormat",
    "QueryResults",
    "QueryRowIterator",
    "QueryType",
    "RDFFormat",
    "RdfConfigError",
    "RdfConfigFormat",
    "ReaderMode",
    "ResultConversionFormat",
    "ResultConversionMode",
    "ResultDCTapFormat",
    "ResultDataFormat",
    "ResultPgSchemaValidationFormat",
    "ResultRdfConfigFormat",
    "ResultShaclValidationFormat",
    "ResultShexValidationFormat",
    "Rudof",
    "RudofConfig",
    "RudofError",
    "SchemaFormat",
    "ServiceDescriptionFormat",
    "ServiceError",
    "ShExError",
    "ShExFormat",
    "ShExValidationEntry",
    "ShExValidationEntryIterator",
    "ShExValidationReport",
    "ShaclError",
    "ShaclFormat",
    "ShaclValidationEntry",
    "ShaclValidationEntryIterator",
    "ShaclValidationMode",
    "ShaclValidationReport",
    "ShaclValidationSortMode",
    "ShapeMapError",
    "ShapeMapFormat",
    "ShapesGraphSource",
    "ShexValidationSortMode",
    "UnsupportedOperationError",
    "ValidationError",
]

class ComparisonError(RudofError):
    r"""
    A schema comparison failed.
    """
    ...

class ConfigError(RudofError):
    r"""
    Invalid or unreadable rudof configuration.
    """
    ...

class ConversionError(RudofError):
    r"""
    A schema conversion failed.
    """
    ...

class DCTapError(RudofError):
    r"""
    A DCTAP profile could not be read or converted.
    """
    ...

class DataError(RudofError):
    r"""
    RDF data could not be parsed, loaded or serialized.
    """
    ...

@typing.final
class DataGenerator:
    r"""
    Generates synthetic RDF data from a ShEx or SHACL schema.
    """
    def __new__(cls, config: GeneratorConfig) -> DataGenerator:
        r"""
        Creates a new generator with the given configuration.
        
        Args:
            config (GeneratorConfig): Configuration object.
        
        Raises:
            GenerateError: If the generator cannot be initialized.
        """
    def load_shex_schema(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Loads and processes a ShEx schema file.
        
        Args:
            path (str | os.PathLike): Path to the ShEx schema file.
        
        Raises:
            GenerateError: If the schema cannot be loaded or parsed.
        """
    def load_shacl_schema(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Loads and processes a SHACL schema file.
        
        Args:
            path (str | os.PathLike): Path to the SHACL schema file.
        
        Raises:
            GenerateError: If the schema cannot be loaded or parsed.
        """
    def load_schema_auto(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Auto-detects the schema format and loads the file.
        
        Args:
            path (str | os.PathLike): Path to the schema file.
        
        Raises:
            GenerateError: If the schema cannot be loaded or parsed.
        """
    def generate(self) -> None:
        r"""
        Generates synthetic data and writes it to the configured output.
        
        Raises:
            GenerateError: If data generation fails.
        """
    def run_with_format(self, schema_path: builtins.str | os.PathLike | pathlib.Path, format: typing.Optional[SchemaFormat] = None) -> None:
        r"""
        Runs the whole pipeline: load the schema, then generate.
        
        Args:
            schema_path (str | os.PathLike): Path to the schema file.
            format (SchemaFormat, optional): Schema format. Auto-detected when omitted.
        
        Raises:
            GenerateError: If schema loading or generation fails.
        """
    def run(self, schema_path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Runs the whole pipeline with automatic schema format detection.
        
        Args:
            schema_path (str | os.PathLike): Path to the schema file.
        
        Raises:
            GenerateError: If schema loading or generation fails.
        """
    def __repr__(self) -> builtins.str: ...

class GenerateError(RudofError):
    r"""
    Synthetic data generation failed.
    """
    ...

@typing.final
class GeneratorConfig:
    r"""
    Configuration for synthetic data generation.
    """
    def __new__(cls) -> GeneratorConfig: ...
    @staticmethod
    def from_toml_file(path: builtins.str | os.PathLike | pathlib.Path) -> GeneratorConfig:
        r"""
        Loads configuration from a TOML file.
        
        Args:
            path (str | os.PathLike): Path to the TOML configuration file.
        
        Returns:
            GeneratorConfig: Loaded configuration object.
        
        Raises:
            GenerateError: If the file cannot be read or parsed.
        """
    @staticmethod
    def from_json_file(path: builtins.str | os.PathLike | pathlib.Path) -> GeneratorConfig:
        r"""
        Loads configuration from a JSON file.
        
        Args:
            path (str | os.PathLike): Path to the JSON configuration file.
        
        Returns:
            GeneratorConfig: Loaded configuration object.
        
        Raises:
            GenerateError: If the file cannot be read or parsed.
        """
    def to_toml_file(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Saves this configuration to a TOML file.
        
        Args:
            path (str | os.PathLike): Path where the TOML file will be written.
        
        Raises:
            GenerateError: If writing to the file fails.
        """
    def set_entity_count(self, count: builtins.int) -> None:
        r"""
        Sets the number of entities to generate.
        """
    def get_entity_count(self) -> builtins.int:
        r"""
        Returns the number of entities to generate.
        """
    def set_seed(self, seed: typing.Optional[builtins.int]) -> None:
        r"""
        Sets the random seed for reproducible generation.
        """
    def get_seed(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the random seed, if one is set.
        """
    def set_schema_format(self, format: typing.Optional[SchemaFormat]) -> None:
        r"""
        Sets the schema format. ``None`` means auto-detect.
        """
    def set_cardinality_strategy(self, strategy: CardinalityStrategy) -> None:
        r"""
        Sets the strategy used to pick cardinalities.
        """
    def set_entity_distribution(self, distribution: EntityDistribution) -> None:
        r"""
        Sets how entities are distributed across shapes.
        """
    def set_output_path(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Sets the output file path.
        """
    def get_output_path(self) -> builtins.str:
        r"""
        Returns the output file path.
        """
    def set_output_format(self, format: OutputFormat) -> None:
        r"""
        Sets the output serialization format.
        """
    def set_compress(self, compress: builtins.bool) -> None:
        r"""
        Enables or disables compression of the output.
        """
    def get_compress(self) -> builtins.bool:
        r"""
        Returns whether the output is compressed.
        """
    def set_write_stats(self, write_stats: builtins.bool) -> None:
        r"""
        Enables or disables writing a statistics file alongside the output.
        """
    def get_write_stats(self) -> builtins.bool:
        r"""
        Returns whether a statistics file is written.
        """
    def set_parallel_writing(self, parallel_writing: builtins.bool) -> None:
        r"""
        Enables or disables writing the output from several threads.
        """
    def get_parallel_writing(self) -> builtins.bool:
        r"""
        Returns whether the output is written in parallel.
        """
    def set_parallel_file_count(self, count: builtins.int) -> None:
        r"""
        Sets how many files parallel writing splits the output into.
        """
    def get_parallel_file_count(self) -> builtins.int:
        r"""
        Returns how many files parallel writing splits the output into.
        """
    def set_worker_threads(self, threads: typing.Optional[builtins.int]) -> None:
        r"""
        Sets the number of worker threads. ``None`` uses the runtime default.
        """
    def get_worker_threads(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the configured number of worker threads.
        """
    def set_batch_size(self, batch_size: builtins.int) -> None:
        r"""
        Sets the batch size used by parallel processing.
        """
    def get_batch_size(self) -> builtins.int:
        r"""
        Returns the batch size used by parallel processing.
        """
    def set_parallel_shapes(self, enabled: builtins.bool) -> None:
        r"""
        Enables or disables processing shapes in parallel.
        """
    def get_parallel_shapes(self) -> builtins.bool:
        r"""
        Returns whether shapes are processed in parallel.
        """
    def set_parallel_fields(self, enabled: builtins.bool) -> None:
        r"""
        Enables or disables processing fields in parallel.
        """
    def get_parallel_fields(self) -> builtins.bool:
        r"""
        Returns whether fields are processed in parallel.
        """
    def set_locale(self, locale: builtins.str) -> None:
        r"""
        Sets the locale used by the default field generators.
        """
    def get_locale(self) -> builtins.str:
        r"""
        Returns the locale used by the default field generators.
        """
    def set_data_quality(self, quality: DataQuality) -> None:
        r"""
        Sets how realistic the generated values should be.
        """
    def validate(self) -> None:
        r"""
        Validates the configuration.
        
        Raises:
            GenerateError: If the configuration is invalid.
        """
    def show(self) -> builtins.str:
        r"""
        Returns a debug rendering of the whole configuration.
        """
    def __repr__(self) -> builtins.str: ...

class InputError(RudofError):
    r"""
    An input string, path or URL could not be resolved.
    """
    ...

class InternalError(RudofError):
    r"""
    A Rust panic was caught at the Python boundary. Always a bug in rudof; the session may be left in an inconsistent state, so create a fresh Rudof rather than reusing it.
    """
    ...

class IriError(RudofError):
    r"""
    An IRI was malformed or could not be resolved.
    """
    ...

class MapStateError(RudofError):
    r"""
    A ShEx map state could not be read.
    """
    ...

class MaterializeError(RudofError):
    r"""
    Materialization failed.
    """
    ...

@typing.final
class NeighborArc:
    r"""
    A single arc in a node's neighborhood.
    """
    @property
    def root(self) -> builtins.str:
        r"""
        The node the neighborhood expansion started from.
        
        Raises:
            InternalError: If the term has no string rendering yet. `Display for Object` is
                unimplemented for RDF 1.2 triple terms, so an arc that reaches one panics on
                being formatted; the guard turns that into a catchable error. Remove the
                guard once terms are returned typed instead of pre-rendered.
        """
    @property
    def direction(self) -> ArcDirection:
        r"""
        Whether the arc leaves or enters `node`.
        """
    @property
    def depth(self) -> builtins.int:
        r"""
        How many arcs away from `root` this arc is.
        """
    @property
    def node(self) -> builtins.str:
        r"""
        The node this arc starts from.
        
        Raises:
            InternalError: As :attr:`root`.
        """
    @property
    def predicate(self) -> builtins.str:
        r"""
        The predicate IRI of the arc.
        """
    @property
    def neighbor(self) -> builtins.str:
        r"""
        The node on the other end of the arc.
        
        Raises:
            InternalError: As :attr:`root`. This is the getter RDF 1.2 data actually reaches:
                a reifier's ``rdf:reifies`` arc has a triple term as its neighbor.
        """
    @property
    def is_last(self) -> builtins.bool:
        r"""
        ``True`` if this is the last arc of the node it expands.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class NeighborArcIterator:
    r"""
    Iterator over the arcs around a node, in depth-first order.
    
    The arcs are collected by :meth:`Rudof.node_neighborhood` before this object exists, so
    ``__length_hint__`` is exact rather than a hint.
    """
    @property
    def truncated(self) -> builtins.bool:
        r"""
        ``True`` when a ``limit`` cut the neighborhood short, so more arcs exist than this
        iterator will yield. Always ``False`` when no ``limit`` was given.
        """
    def __iter__(self) -> NeighborArcIterator: ...
    def __next__(self) -> NeighborArc: ...
    def __length_hint__(self) -> builtins.int:
        r"""
        The number of arcs still to be yielded. Exact, not an estimate.
        """

class NodeInspectionError(RudofError):
    r"""
    A node could not be inspected.
    """
    ...

class PgDbError(RudofError):
    r"""
    A property-graph database operation failed.
    """
    ...

class PgSchemaError(RudofError):
    r"""
    A property-graph schema could not be parsed or serialized.
    """
    ...

@typing.final
class PgSchemaValidationEntry:
    r"""
    One ``(node, type)`` association of a property graph schema validation result.
    """
    @property
    def node_id(self) -> builtins.str:
        r"""
        The identifier of the node that was checked.
        """
    @property
    def type_name(self) -> builtins.str:
        r"""
        The name of the type it was checked against.
        """
    @property
    def conforms(self) -> builtins.bool:
        r"""
        ``True`` when the node conforms to the type.
        """
    @property
    def details(self) -> builtins.str:
        r"""
        The errors that made it fail, or the evidences that made it pass, joined by ``"; "``.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PgSchemaValidationEntryIterator:
    r"""
    Iterator over a :class:`PgSchemaValidationReport`'s entries.
    """
    def __iter__(self) -> PgSchemaValidationEntryIterator: ...
    def __next__(self) -> PgSchemaValidationEntry: ...
    def __length_hint__(self) -> builtins.int: ...

@typing.final
class PgSchemaValidationReport:
    r"""
    The result of the most recent :meth:`Rudof.validate_pgschema` call.
    
    A snapshot: it owns its data and is unaffected by later calls on the session.
    """
    @property
    def conforms(self) -> builtins.bool:
        r"""
        ``True`` if every association conforms.
        
        Reported by the validator, not derived from the entries.
        """
    @property
    def violations(self) -> builtins.list[PgSchemaValidationEntry]:
        r"""
        The associations that do **not** conform.
        """
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> PgSchemaValidationEntryIterator: ...
    def __bool__(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class PrefixesError(RudofError):
    r"""
    A prefix declaration operation failed.
    """
    ...

class QueryError(RudofError):
    r"""
    A SPARQL query failed to parse or execute.
    """
    ...

@typing.final
class QueryResults:
    r"""
    The result of the most recent :meth:`Rudof.run_query` call.
    
    The three query shapes are not interchangeable, so the container protocol is only
    offered where it means something:
    
    ==========  ==================  =========================  =====================
    query       ``len()``           iteration                  ``bool()``
    ==========  ==================  =========================  =====================
    SELECT      solutions           one dict per solution      any solution
    ASK         ``TypeError``       ``TypeError``              the answer
    CONSTRUCT   ``TypeError``       ``TypeError``              any triple
    ==========  ==================  =========================  =====================
    
    ``len()`` and iteration always agree. ``bool()`` is defined for every shape, so
    ``if results:`` is the one test that works everywhere.
    """
    @property
    def variables(self) -> builtins.list[builtins.str]:
        r"""
        The projected variable names, in SELECT order. Empty for ASK and CONSTRUCT.
        """
    @property
    def rows(self) -> builtins.list[builtins.list[typing.Optional[builtins.str]]]:
        r"""
        One list of cells per solution, aligned with :attr:`variables`. Empty for ASK and
        CONSTRUCT.
        """
    @property
    def boolean(self) -> typing.Optional[builtins.bool]:
        r"""
        The answer to an ASK query, or ``None`` for every other query type.
        """
    @property
    def graph(self) -> typing.Optional[builtins.str]:
        r"""
        The serialized graph of a CONSTRUCT or DESCRIBE query, or ``None`` otherwise.
        
        A string, in the serialization :meth:`Rudof.run_query` produced — Turtle today. It is
        not parsed, which is why the result has no triple count and does not iterate; to
        consume the triples, load the string into another :class:`Rudof`.
        """
    @property
    def is_boolean(self) -> builtins.bool:
        r"""
        ``True`` when the result is the answer to an ASK query.
        """
    @property
    def is_graph(self) -> builtins.bool:
        r"""
        ``True`` when the result is a graph, from a CONSTRUCT or DESCRIBE query.
        """
    def to_python(self) -> typing.Any:
        r"""
        The result as plain Python: a list of dicts for SELECT, a ``bool`` for ASK, a ``str`` for CONSTRUCT and DESCRIBE.
        """
    def __len__(self) -> builtins.int:
        r"""
        The number of solutions of a SELECT.
        
        Only a SELECT result is a collection, so only a SELECT has a length, and it always
        agrees with what iteration yields.
        
        Raises:
            TypeError: For an ASK result, which is one boolean rather than a collection, and
                for a CONSTRUCT or DESCRIBE, whose graph is an unparsed string. Use
                :attr:`boolean` or :attr:`graph`; ``bool(results)`` works for every type.
        """
    def __iter__(self) -> QueryRowIterator:
        r"""
        Iterates a SELECT's solutions, one dict per solution.
        
        Raises:
            TypeError: For an ASK, CONSTRUCT or DESCRIBE result, as :meth:`__len__`.
        """
    def __bool__(self) -> builtins.bool:
        r"""
        Whether the query returned anything: the answer for an ASK, and whether any solution
        or triple came back otherwise.
        
        Defined explicitly so `if results:` works for every query type, including the ones
        whose :meth:`__len__` raises — Python would otherwise fall back to ``__len__``.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class QueryRowIterator:
    r"""
    Iterator over a :class:`QueryResults`' solutions, one dict per solution.
    """
    def __iter__(self) -> QueryRowIterator: ...
    def __next__(self) -> builtins.dict[builtins.str, typing.Optional[builtins.str]]: ...
    def __length_hint__(self) -> builtins.int: ...

class RdfConfigError(RudofError):
    r"""
    An rdf-config document could not be read or written.
    """
    ...

@typing.final
class Rudof:
    r"""
    Main interface for working with Semantic Web operations.
    
    A stateful session: loaded data, schemas and results persist across calls until a
    ``reset_*`` method clears them.
    """
    def compare_schemas(self, schema1: builtins.str | os.PathLike[str], schema2: builtins.str | os.PathLike[str], mode1: builtins.str, mode2: builtins.str, format1: builtins.str, format2: builtins.str, base1: typing.Optional[builtins.str] = None, base2: typing.Optional[builtins.str] = None, label1: typing.Optional[builtins.str] = None, label2: typing.Optional[builtins.str] = None, reader_mode: typing.Optional[ReaderMode] = None) -> builtins.str:
        r"""
        Compares two schemas for structural equivalence.
        
        Converts both schemas to the Common Shapes Model and performs a structural comparison.
        
        Args:
            schema1 (str | os.PathLike): First schema — inline, file path or URL.
            schema2 (str | os.PathLike): Second schema — inline, file path or URL.
            mode1 (str): First schema type, e.g. ``"shex"``, ``"shacl"``, ``"dctap"``, ``"service"``.
            mode2 (str): Second schema type.
            format1 (str): First schema format, e.g. ``"shexc"``, ``"turtle"``.
            format2 (str): Second schema format.
            base1 (str, optional): Base IRI for the first schema.
            base2 (str, optional): Base IRI for the second schema.
            label1 (str, optional): Shape label to compare in the first schema.
            label2 (str, optional): Shape label to compare in the second schema.
            reader_mode (ReaderMode, optional): Error handling. Defaults to ``ReaderMode.Lax``.
        
        Returns:
            str: Comparison result showing the differences.
        
        Raises:
            ComparisonError: If a mode or format name is not recognized, or the comparison fails.
            InputError: If either schema cannot be resolved.
        """
    def convert_schemas(self, schema: builtins.str | os.PathLike[str], input_mode: ConversionMode, output_mode: ResultConversionMode, input_format: ConversionFormat, output_format: ResultConversionFormat, base: typing.Optional[builtins.str] = None, reader_mode: typing.Optional[ReaderMode] = None, shape: typing.Optional[builtins.str] = None, templates_folder: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, output_folder: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None) -> builtins.str:
        r"""
        Converts a schema from one language to another.
        
        Args:
            schema (str | os.PathLike): Schema to convert — inline, file path or URL.
            input_mode (ConversionMode): The language of the input schema.
            output_mode (ResultConversionMode): The target language.
            input_format (ConversionFormat): The serialization of the input schema.
            output_format (ResultConversionFormat): The serialization of the output.
            base (str, optional): Base IRI for resolving relative IRIs.
            reader_mode (ReaderMode, optional): Error handling. Defaults to ``ReaderMode.Lax``.
            shape (str, optional): Restrict the conversion to a single shape.
            templates_folder (str | os.PathLike, optional): Folder of templates used by the HTML output mode.
            output_folder (str | os.PathLike, optional): Folder to write multi-file output into.
        
        Returns:
            str: The converted schema.
        
        Raises:
            InputError: If the schema cannot be resolved.
            ConversionError: If the conversion fails.
        """
    def read_data(self, input: typing.Optional[builtins.str | os.PathLike[str]] = None, format: typing.Optional[RDFFormat] = None, base: typing.Optional[builtins.str] = None, reader_mode: typing.Optional[ReaderMode] = None, merge: typing.Optional[builtins.bool] = None, endpoint: typing.Optional[builtins.str] = None) -> None:
        r"""
        Loads RDF data from a string, file path or URL. If a SPARQL endpoint is
        specified, it loads data from the endpoint instead.
        
        Args:
            input (str | os.PathLike, optional): Inline data, file path or URL to the RDF
                data. Examples: ``"data.ttl"``, ``"http://example.org/data.rdf"``.
            format (RDFFormat, optional): Serialization format. Defaults to ``RDFFormat.Turtle``.
            base (str, optional): Base IRI for resolving relative IRIs.
            reader_mode (ReaderMode, optional): Error handling strategy. Defaults to ``ReaderMode.Lax``.
                - ``Lax``: Continue on errors
                - ``Strict``: Fail on first error
            merge (bool, optional): If ``True``, merge with existing data; if ``False``, replace current data.
                Defaults to ``False``.
            endpoint (str, optional): SPARQL endpoint URL to load data from. If provided, it overrides the ``input``
                parameter.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            DataError: If the data is malformed (in Strict mode).
        """
    def serialize_data(self, format: typing.Optional[ResultDataFormat] = None) -> builtins.str:
        r"""
        Serializes the current RDF data to a string.
        
        Args:
            format (ResultDataFormat, optional): Output format. Defaults to ``ResultDataFormat.Compact``.
        
        Returns:
            str: Serialized RDF data.
        
        Raises:
            DataError: If serialization fails.
        """
    def dereference(self, uri: builtins.str, reader_mode: typing.Optional[ReaderMode] = None, merge: typing.Optional[builtins.bool] = None) -> None:
        r"""
        Dereferences an IRI and adds the retrieved triples to the current graph.
        
        Args:
            uri (str): The IRI to dereference.
            reader_mode (ReaderMode, optional): Error handling strategy. Defaults to ``ReaderMode.Lax``.
            merge (bool, optional): If ``True``, merge with existing data; if ``False``,
                replace current data. Defaults to ``False``.
        
        Raises:
            DataError: If the IRI cannot be dereferenced or the response is malformed.
        """
    def read_dctap(self, input: builtins.str | os.PathLike[str], format: typing.Optional[DCTapFormat] = None) -> None:
        r"""
        Loads a DCTAP profile from a string, file path or URL.
        
        Args:
            input (str | os.PathLike): Inline profile, file path or URL.
            format (DCTapFormat, optional): Input format. Defaults to ``DCTapFormat.Csv``.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            DCTapError: If the profile is malformed.
        """
    def serialize_dctap(self, format: typing.Optional[ResultDCTapFormat] = None) -> builtins.str:
        r"""
        Serializes the current DCTAP profile to a string.
        
        Args:
            format (ResultDCTapFormat, optional): Output format. Defaults to ``ResultDCTapFormat.Internal``.
        
        Returns:
            str: Serialized DCTAP profile.
        
        Raises:
            DCTapError: If no profile is loaded or serialization fails.
        """
    def node_info(self, node_selector: builtins.str, predicates: typing.Optional[typing.Sequence[builtins.str]] = None, mode: typing.Optional[builtins.str] = None, show_colors: typing.Optional[builtins.bool] = None, depth: typing.Optional[builtins.int] = None) -> builtins.str:
        r"""
        Retrieves detailed information about a specific node in the RDF graph.
        
        Provides a neighborhood view of a node, including its properties, outgoing and
        incoming edges, and connected nodes up to a specified depth.
        
        Args:
            node_selector (str): Node identifier. Can be:
                - Full IRI: ``<http://example.org/alice>``
                - Prefixed name: ``:alice``
                - Blank node: ``_:b1``
            predicates (list[str], optional): Filter by specific predicates. Empty list means all predicates.
            mode (str, optional): Node inspection mode — ``"outgoing"``, ``"incoming"`` or ``"both"``. Defaults to ``"both"``.
            show_colors (bool, optional): Use ANSI terminal colors in output. Defaults to ``True``.
            depth (int, optional): Neighborhood distance (1 = direct neighbors, 2 = neighbors of neighbors, ...).
                Defaults to ``1``.
        
        Returns:
            str: Formatted string with node information and neighborhood graph.
        
        Raises:
            NodeInspectionError: If the mode is not one of the three accepted values, or
                the node selector is invalid.
        
        Note:
            Colors require a terminal with ANSI escape sequence support.
        """
    def node_neighborhood(self, node_selector: builtins.str, predicates: typing.Optional[typing.Sequence[builtins.str]] = None, mode: typing.Optional[builtins.str] = None, depth: typing.Optional[builtins.int] = None, strict_iris: typing.Optional[builtins.bool] = None, limit: typing.Optional[builtins.int] = None) -> NeighborArcIterator:
        r"""
        Returns an iterator over the arcs around a node, in depth-first order.
        
        Args:
            node_selector (str): Node identifier, as in :meth:`node_info`.
            predicates (list[str], optional): Filter by specific predicates. Each entry must
                be an angle-bracketed IRI (``<http://example.org/p>``) or a prefixed name
                (``:p``). A bare IRI is **not** accepted here, even with the default
                ``strict_iris=False``, which relaxes ``node_selector`` only.
            mode (str, optional): ``"outgoing"``, ``"incoming"`` or ``"both"``. Defaults to ``"both"``.
            depth (int, optional): Neighborhood distance. Defaults to ``1``.
            strict_iris (bool, optional): Require angle-bracketed IRIs in ``node_selector``
                instead of auto-wrapping bare ones. Defaults to ``False``.
            limit (int, optional): Stop after this many arcs. Unbounded when omitted.
        
        Returns:
            NeighborArcIterator: The arcs around the node.
        
        Raises:
            NodeInspectionError: If the mode is invalid.
            DataError: If an arc cannot be retrieved, or a predicate is a bare IRI.
        
        Note:
            The arcs are materialized before this returns, so a hub node queried without
            ``limit`` allocates its whole fanout and breaking out of the loop early saves
            nothing. Pass ``limit`` to bound the work and check
            :attr:`NeighborArcIterator.truncated` to learn whether it cut the result short.
        """
    def read_map_state(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Loads a MapState from a JSON file.
        
        The MapState records the bindings produced by ShEx validation with Map semantic
        actions. It is required before calling :meth:`materialize`.
        
        Args:
            path (str | os.PathLike): Path to the JSON file containing the serialized MapState.
        
        Raises:
            MapStateError: If the file cannot be read or the JSON is malformed.
        """
    def materialize(self, format: typing.Optional[ResultDataFormat] = None, node: typing.Optional[builtins.str] = None) -> builtins.str:
        r"""
        Materializes an RDF graph from the current ShEx schema and MapState.
        
        Uses the Map semantic-action state (loaded via :meth:`read_map_state` or set
        after ShEx validation) to populate the triples defined by the ShEx schema's Map
        extensions.
        
        Args:
            format (ResultDataFormat, optional): RDF serialization format for the output
                graph. Defaults to ``ResultDataFormat.Turtle``.
            node (str, optional): IRI string used as the root subject node of the
                materialized graph. A fresh blank node is minted when omitted.
        
        Returns:
            str: Serialized RDF graph.
        
        Raises:
            MaterializeError: If no ShEx schema or MapState is loaded, if the node IRI is
                invalid, or if materialization or serialization fails.
        """
    def connect_pg_db(self, path: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, in_memory: builtins.bool = False, read_only: builtins.bool = False, engine: typing.Optional[DbEngine] = None) -> None:
        r"""
        Opens (creating if necessary) a property graph database and stores the connection
        so :meth:`load_pg_db` / :meth:`query_cypher` can reuse it without repeating the
        path.
        
        Args:
            path (str | os.PathLike, optional): Path to the database directory. Required unless ``in_memory=True``.
            in_memory (bool, optional): Create a transient in-memory database. Its connection cannot be reused,
                since it does not outlive the process. Defaults to ``False``.
            read_only (bool, optional): Open the database in read-only mode. Defaults to ``False``.
            engine (DbEngine, optional): Database engine. Defaults to ``DbEngine.Lbug``, the only one supported today.
        
        Raises:
            PgDbError: If the database cannot be opened.
        """
    def pg_db_ddl(self, data: builtins.str | os.PathLike[str], dialect: typing.Optional[DdlDialect] = None, graph_type_name: typing.Optional[builtins.str] = None, format: typing.Optional[RDFFormat] = None, base: typing.Optional[builtins.str] = None) -> builtins.str:
        r"""
        Derives a property graph schema from RDF data and emits it as DDL.
        
        Args:
            data (str | os.PathLike): Inline data, file path or URL to the RDF data.
            dialect (DdlDialect, optional): Target DDL dialect. Defaults to ``DdlDialect.Cypher``.
            graph_type_name (str, optional): Graph type name used by the ``gql`` dialect. Defaults to ``"rudof_graph"``.
            format (RDFFormat, optional): RDF data format. Defaults to ``RDFFormat.Turtle``.
            base (str, optional): Base IRI for the data.
        
        Returns:
            str: The generated DDL.
        
        Raises:
            InputError: If the data cannot be resolved.
            PgDbError: If the data cannot be parsed.
        """
    def load_pg_db(self, data: builtins.str | os.PathLike[str], shapes: typing.Optional[builtins.str | os.PathLike[str]] = None, skip_validation: builtins.bool = False, db: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, format: typing.Optional[RDFFormat] = None, base: typing.Optional[builtins.str] = None) -> builtins.str:
        r"""
        Loads RDF data, validates it against SHACL shapes (unless ``skip_validation``),
        derives a property graph schema, and copies the data into the connected database.
        
        Args:
            data (str | os.PathLike): Inline data, file path or URL to the RDF data.
            shapes (str | os.PathLike, optional): Inline shapes, file path or URL to SHACL shapes. If not given,
                shapes embedded in the data itself are used.
            skip_validation (bool, optional): Skip SHACL validation and just copy the data
                — the database DDL enforces conformance. Defaults to ``False``.
            db (str | os.PathLike, optional): Path overriding the database connected via
                :meth:`connect_pg_db`.
            format (RDFFormat, optional): RDF data format. Defaults to ``RDFFormat.Turtle``.
            base (str, optional): Base IRI for the data.
        
        Returns:
            str: Progress text describing what was loaded, validated, and inserted.
        
        Raises:
            PgDbError: If no database is connected or loading fails.
            ValidationError: If SHACL validation fails.
        """
    def query_cypher(self, query: builtins.str | os.PathLike[str], db: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, read_only: builtins.bool = False) -> typing.Any:
        r"""
        Runs a Cypher query against the connected property graph database.
        
        Args:
            query (str | os.PathLike): Inline query, file path or URL.
            db (str | os.PathLike, optional): Path overriding the database connected via :meth:`connect_pg_db`.
            read_only (bool, optional): Open the overriding database in read-only mode. Defaults to ``False``.
        
        Returns:
            dict: ``{"columns": [...], "rows": [...], "compiling_time_ms": float,
            "execution_time_ms": float}``.
        
        Raises:
            PgDbError: If no database is connected or the query fails.
        """
    def read_pgschema(self, input: builtins.str | os.PathLike[str], format: typing.Optional[PgSchemaFormat] = None) -> None:
        r"""
        Loads a property graph schema from a string, file path or URL.
        
        Args:
            input (str | os.PathLike): Inline schema, file path or URL.
            format (PgSchemaFormat, optional): Schema format. Defaults to ``PgSchemaFormat.PgSchemaC``.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            PgSchemaError: If the schema cannot be parsed.
        """
    def serialize_pgschema(self, format: typing.Optional[PgSchemaFormat] = None) -> builtins.str:
        r"""
        Serializes the current property graph schema to a string.
        
        Args:
            format (PgSchemaFormat, optional): Output format. Defaults to ``PgSchemaFormat.PgSchemaC``.
        
        Returns:
            str: Serialized property graph schema.
        
        Raises:
            PgSchemaError: If no schema is loaded or serialization fails.
        """
    def read_typemap(self, input: builtins.str | os.PathLike[str]) -> None:
        r"""
        Loads a typemap (node -> PG schema type bindings) from a string, file path or URL.
        
        Required before calling :meth:`validate_pgschema`.
        
        Args:
            input (str | os.PathLike): Inline typemap, file path or URL.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            PgSchemaError: If the typemap cannot be parsed.
        """
    def validate_pgschema(self) -> PgSchemaValidationReport:
        r"""
        Validates the current property graph data against the loaded PG schema and typemap.
        
        Returns:
            PgSchemaValidationReport: A snapshot of the result — ``.conforms``,
            ``.violations``, ``len()`` and iteration. Unaffected by later calls on the
            session.
        
        Raises:
            ValidationError: If no data, PG schema, or typemap is loaded.
        """
    def serialize_pgschema_validation_results(self, format: typing.Optional[ResultPgSchemaValidationFormat] = None) -> builtins.str:
        r"""
        Serializes the results of the most recent :meth:`validate_pgschema` call.
        
        Args:
            format (ResultPgSchemaValidationFormat, optional): Output format. Defaults to
                ``ResultPgSchemaValidationFormat.Compact``.
        
        Returns:
            str: Serialized validation results.
        
        Raises:
            ValidationError: If there are no results to serialize.
        """
    def prefixes(self) -> builtins.list[tuple[builtins.str, builtins.str]]:
        r"""
        Returns the current default prefix map.
        
        These are the prefix declarations assumed and prepended by default to RDF data,
        SPARQL queries, ShEx schemas and SHACL shapes.
        
        Returns:
            list[tuple[str, str]]: ``(alias, iri)`` tuples.
        """
    def add_prefix(self, alias: builtins.str, iri: builtins.str) -> None:
        r"""
        Adds a prefix declaration to the default prefix map.
        
        Args:
            alias (str): The prefix alias, without the trailing colon.
            iri (str): The IRI the alias expands to.
        
        Raises:
            PrefixesError: If the alias is already declared or the IRI is malformed.
        """
    def remove_prefix(self, alias: builtins.str) -> None:
        r"""
        Removes a prefix declaration from the default prefix map.
        
        Args:
            alias (str): The prefix alias to remove.
        
        Raises:
            PrefixesError: If the alias is not declared.
        """
    def rename_prefix(self, old_alias: builtins.str, new_alias: builtins.str) -> None:
        r"""
        Renames a prefix alias, keeping its IRI.
        
        Args:
            old_alias (str): The alias to rename.
            new_alias (str): The new alias.
        
        Raises:
            PrefixesError: If ``old_alias`` is not declared or ``new_alias`` already is.
        """
    def copy_prefix(self, old_alias: builtins.str, new_alias: builtins.str) -> None:
        r"""
        Declares ``new_alias`` for the same IRI as ``old_alias``, keeping both.
        
        Args:
            old_alias (str): The alias to copy.
            new_alias (str): The new alias.
        
        Raises:
            PrefixesError: If ``old_alias`` is not declared or ``new_alias`` already is.
        """
    def read_query(self, input: builtins.str | os.PathLike[str], query_type: typing.Optional[QueryType] = None) -> None:
        r"""
        Loads a SPARQL query from a string, file path or URL.
        
        Args:
            input (str | os.PathLike): Inline query, file path or URL.
            query_type (QueryType, optional): Type of SPARQL query. Auto-detected when omitted.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            QueryError: If the query is malformed.
        """
    def run_query(self) -> QueryResults:
        r"""
        Executes the loaded query against the loaded data.
        
        Returns:
            QueryResults: A snapshot of the result. A SELECT fills ``variables`` and
            ``rows``, an ASK fills ``boolean``, and a CONSTRUCT or DESCRIBE fills ``graph``.
        
        Raises:
            QueryError: If no query is loaded, or execution fails.
        """
    def serialize_query_results(self, format: typing.Optional[QueryResultFormat] = None) -> builtins.str:
        r"""
        Serializes the results of the most recent :meth:`run_query` call to a string.
        
        Args:
            format (QueryResultFormat, optional): Output format. Defaults to ``QueryResultFormat.Internal``.
        
        Returns:
            str: Serialized query results.
        
        Raises:
            QueryError: If there are no results, or serialization fails.
        """
    def list_endpoints(self) -> builtins.list[tuple[builtins.str, builtins.str]]:
        r"""
        Lists known SPARQL endpoints.
        
        Returns:
            list[tuple[str, str]]: ``(name, url)`` tuples for known endpoints.
        
        Raises:
            QueryError: If the endpoint registry cannot be read.
        """
    def read_rdf_config(self, input: builtins.str | os.PathLike[str], format: typing.Optional[RdfConfigFormat] = None) -> None:
        r"""
        Loads an rdf-config document from a string, file path or URL.
        
        Args:
            input (str | os.PathLike): Inline document, file path or URL.
            format (RdfConfigFormat, optional): Input format. Defaults to ``RdfConfigFormat.Yaml``.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            RdfConfigError: If the document is malformed.
        """
    def serialize_rdf_config(self, format: typing.Optional[ResultRdfConfigFormat] = None) -> builtins.str:
        r"""
        Serializes the current rdf-config document to a string.
        
        Args:
            format (ResultRdfConfigFormat, optional): Output format. Defaults to ``ResultRdfConfigFormat.Internal``.
        
        Returns:
            str: Serialized rdf-config document.
        
        Raises:
            RdfConfigError: If no document is loaded or serialization fails.
        """
    def read_service_description(self, input: builtins.str | os.PathLike[str], format: typing.Optional[RDFFormat] = None, base: typing.Optional[builtins.str] = None, reader_mode: typing.Optional[ReaderMode] = None) -> None:
        r"""
        Loads a service description from a string, file path or URL.
        
        Args:
            input (str | os.PathLike): Inline description, file path or URL, in RDF.
            format (RDFFormat, optional): RDF format. Defaults to ``RDFFormat.Turtle``.
            base (str, optional): Base IRI for resolving relative IRIs.
            reader_mode (ReaderMode, optional): Error handling. Defaults to ``ReaderMode.Lax``.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            ServiceError: If the description is malformed.
        """
    def serialize_service_description(self, format: typing.Optional[ServiceDescriptionFormat] = None) -> builtins.str:
        r"""
        Serializes the current service description to a string.
        
        Args:
            format (ServiceDescriptionFormat, optional): Output format. Defaults to ``ServiceDescriptionFormat.Internal``.
        
        Returns:
            str: Serialized service description.
        
        Raises:
            ServiceError: If no description is loaded or serialization fails.
        """
    def __new__(cls, config: typing.Optional[RudofConfig] = None) -> Rudof:
        r"""
        Creates a new Rudof instance.
        
        Args:
            config (RudofConfig, optional): Configuration for the instance. Defaults to ``RudofConfig()``.
        """
    def update_config(self, config: RudofConfig) -> None:
        r"""
        Updates the configuration of this Rudof instance.
        
        Args:
            config (RudofConfig): New configuration to apply.
        
        Note:
            This does not affect already-loaded data or schemas, only future operations.
        """
    def get_version(self) -> builtins.str:
        r"""
        Returns the version of the underlying rudof library.
        """
    def __repr__(self) -> builtins.str: ...
    def __enter__(self) -> Rudof: ...
    def __exit__(self, _exc_type: typing.Optional[typing.Any] = None, _exc_value: typing.Optional[typing.Any] = None, _traceback: typing.Optional[typing.Any] = None) -> builtins.bool: ...
    def reset_all(self) -> None:
        r"""
        Resets all current state (data, schemas, queries, validation results).
        
        Equivalent to calling every individual reset method.
        """
    def reset_data(self) -> None:
        r"""
        Clears the current RDF data graph.
        
        Removes all RDF triples from memory. Does not affect loaded schemas or other state.
        """
    def reset_shex(self) -> None:
        r"""
        Resets ShEx validation.
        
        Unloads the ShEx schema, ShapeMap, compiled validator, and validation results.
        Does not affect RDF data or other state. Use :meth:`reset_shex_schema` instead to
        unload only the schema, keeping any loaded ShapeMap and validation results.
        """
    def reset_shex_schema(self) -> None:
        r"""
        Clears the current ShEx schema only.
        
        Unlike :meth:`reset_shex`, this leaves any loaded ShapeMap and ShEx validation results untouched.
        """
    def reset_shacl(self) -> None:
        r"""
        Clears the current SHACL shapes graph only.
        
        Unloads the SHACL shapes from memory, leaving any existing SHACL validation
        results untouched. Use :meth:`reset_shacl_validation` instead to also clear
        validation results.
        """
    def reset_shacl_validation(self) -> None:
        r"""
        Resets SHACL validation.
        
        Clears SHACL validation results and unloads the currently loaded SHACL shapes
        graph. Use :meth:`reset_shacl` instead to unload only the shapes graph, keeping
        any validation results.
        """
    def reset_shapemap(self) -> None:
        r"""
        Clears the current ShapeMap.
        
        Removes the ShapeMap used for ShEx validation.
        """
    def reset_query(self) -> None:
        r"""
        Clears the current SPARQL query.
        
        Removes the stored query from memory.
        """
    def reset_query_results(self) -> None:
        r"""
        Clears the results of the most recent SPARQL query.
        
        Leaves the query itself loaded.
        """
    def reset_dctap(self) -> None:
        r"""
        Clears the current DCTAP profile.
        """
    def reset_rdf_config(self) -> None:
        r"""
        Clears the current rdf-config document.
        """
    def reset_service_description(self) -> None:
        r"""
        Clears the current service description.
        """
    def reset_pgschema(self) -> None:
        r"""
        Clears the current property graph schema.
        """
    def reset_typemap(self) -> None:
        r"""
        Clears the current property graph type map.
        """
    def reset_pgschema_validation(self) -> None:
        r"""
        Clears the results of the most recent property graph schema validation.
        """
    def reset_pg_db_connection(self) -> None:
        r"""
        Closes and forgets the current property graph database connection.
        """
    def reset_validation_results(self) -> None:
        r"""
        Resets validation state across all domains.
        
        Equivalent to calling :meth:`reset_shex`, :meth:`reset_shacl_validation` and
        :meth:`reset_pgschema_validation` together: clears ShEx, SHACL and Property Graph
        schema validation results, along with their associated loaded schemas and
        ShapeMaps.
        """
    def read_shacl(self, input: typing.Optional[builtins.str | os.PathLike[str]] = None, format: typing.Optional[ShaclFormat] = None, base: typing.Optional[builtins.str] = None, reader_mode: typing.Optional[ReaderMode] = None) -> None:
        r"""
        Loads a SHACL shapes graph from a string, file path or URL.
        
        Args:
            input (str | os.PathLike, optional): Inline shapes, file path or URL. If not provided, the shapes are
                extracted from the currently loaded data.
            format (ShaclFormat, optional): RDF format. Defaults to ``ShaclFormat.Turtle``.
            base (str, optional): Base IRI for resolving relative IRIs.
            reader_mode (ReaderMode, optional): Error handling. Defaults to ``ReaderMode.Lax``.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            ShaclError: If the shapes graph is malformed.
        """
    def serialize_shacl(self, format: typing.Optional[ShaclFormat] = None) -> builtins.str:
        r"""
        Serializes the current SHACL shapes graph to a string.
        
        Args:
            format (ShaclFormat, optional): Output format. Defaults to ``ShaclFormat.Turtle``.
        
        Returns:
            str: Serialized shapes graph.
        
        Raises:
            ShaclError: If no shapes are loaded or serialization fails.
        """
    def validate_shacl(self, mode: typing.Optional[ShaclValidationMode] = None) -> ShaclValidationReport:
        r"""
        Validates the current RDF data against the loaded SHACL shapes.
        
        Args:
            mode (ShaclValidationMode, optional): Validation engine. Defaults to ``ShaclValidationMode.Native``.
                - ``Native``: Fast built-in engine (recommended for production)
                - ``Sparql``: SPARQL-based engine
        
        Returns:
            ShaclValidationReport: A snapshot of the result — ``.conforms``,
            ``.violations``, ``len()`` and iteration. Unaffected by later calls on the
            session.
        
        Raises:
            ValidationError: If no data or schema is loaded, or validation fails.
        """
    def serialize_shacl_validation_results(self, format: typing.Optional[ResultShaclValidationFormat] = None, sort_mode: typing.Optional[ShaclValidationSortMode] = None) -> builtins.str:
        r"""
        Serializes the results of the most recent :meth:`validate_shacl` call.
        
        Args:
            format (ResultShaclValidationFormat, optional): Output format. Defaults to
                ``ResultShaclValidationFormat.Details``.
            sort_mode (ShaclValidationSortMode, optional): Sorting mode. Defaults to
                ``ShaclValidationSortMode.Severity``.
        
        Returns:
            str: Serialized validation results.
        
        Raises:
            ValidationError: If there are no results to serialize.
        """
    def read_shapemap(self, input: builtins.str | os.PathLike[str], format: typing.Optional[ShapeMapFormat] = None, base_nodes: typing.Optional[builtins.str] = None, base_shapes: typing.Optional[builtins.str] = None) -> None:
        r"""
        Loads a ShapeMap from a string, file path or URL.
        
        Args:
            input (str | os.PathLike): Inline ShapeMap, file path or URL.
            format (ShapeMapFormat, optional): Format. Defaults to ``ShapeMapFormat.Compact``.
            base_nodes (str, optional): Base IRI for resolving node IRIs.
            base_shapes (str, optional): Base IRI for resolving shape IRIs.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            ShapeMapError: If the ShapeMap is malformed.
        """
    def serialize_shapemap(self, format: typing.Optional[ShapeMapFormat] = None) -> builtins.str:
        r"""
        Serializes the current ShapeMap to a string.
        
        Args:
            format (ShapeMapFormat, optional): Output format. Defaults to ``ShapeMapFormat.Compact``.
        
        Returns:
            str: Serialized ShapeMap.
        
        Raises:
            ShapeMapError: If serialization fails.
        """
    def check_shex(self, input: builtins.str | os.PathLike[str], format: typing.Optional[ShExFormat] = None, base: typing.Optional[builtins.str] = None) -> tuple[builtins.bool, builtins.str]:
        r"""
        Checks whether a ShEx schema is well-formed, without loading it into the session.
        
        Parses the schema, compiles it to IR, and checks for negative dependency cycles,
        without affecting any currently loaded schema.
        
        Args:
            input (str | os.PathLike): Inline schema, file path or URL.
            format (ShExFormat, optional): Schema format. Defaults to ``ShExFormat.ShExC``.
            base (str, optional): Base IRI for resolving relative IRIs.
        
        Returns:
            tuple[bool, str]: Whether the schema is well-formed, and a human-readable
            message describing the result (or the error found).
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
        """
    def read_shex(self, input: builtins.str | os.PathLike[str], format: typing.Optional[ShExFormat] = None, base: typing.Optional[builtins.str] = None, reader_mode: typing.Optional[ReaderMode] = None) -> None:
        r"""
        Loads a ShEx schema from a string, file path or URL.
        
        Args:
            input (str | os.PathLike): Inline schema, file path or URL.
            format (ShExFormat, optional): Schema format. Defaults to ``ShExFormat.ShExC``.
            base (str, optional): Base IRI for resolving relative IRIs.
            reader_mode (ReaderMode, optional): Error handling mode. Defaults to ``ReaderMode.Lax``.
        
        Raises:
            InputError: If the input string, file or URL cannot be resolved.
            ShExError: If the schema is malformed.
        """
    def serialize_current_shex(self, shape_label: typing.Optional[builtins.str] = None, show_dependencies: typing.Optional[builtins.bool] = None, show_statistics: typing.Optional[builtins.bool] = None, show_schema: typing.Optional[builtins.bool] = None, show_time: typing.Optional[builtins.bool] = None, format: typing.Optional[ShExFormat] = None) -> builtins.str:
        r"""
        Serializes the current ShEx schema to a string.
        
        Args:
            shape_label (str, optional): Restrict the output to a single shape.
            show_dependencies (bool, optional): Include the shape dependency graph.
            show_statistics (bool, optional): Include schema statistics.
            show_schema (bool, optional): Include the schema itself.
            show_time (bool, optional): Include elapsed time.
            format (ShExFormat, optional): Output format. Defaults to ``ShExFormat.ShExC``.
        
        Returns:
            str: Serialized ShEx schema.
        
        Raises:
            ShExError: If no schema is loaded or serialization fails.
        """
    def compile_shex_to_file(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Writes the currently loaded ShEx schema's compiled IR to a cache file.
        
        The cache can later be loaded quickly with :meth:`read_shex_precompiled`,
        skipping parsing, imports, and AST-to-IR compilation.
        
        Args:
            path (str | os.PathLike): Path of the cache file to write.
        
        Raises:
            ShExError: If no ShEx schema is loaded or the file cannot be written.
        """
    def read_shex_precompiled(self, path: builtins.str | os.PathLike[str], reader_mode: typing.Optional[ReaderMode] = None) -> None:
        r"""
        Loads a precompiled ShEx schema cache produced by :meth:`compile_shex_to_file`.
        
        Args:
            path (str | os.PathLike): Path to the cache file.
            reader_mode (ReaderMode, optional): Error handling mode. Defaults to ``ReaderMode.Lax``.
        
        Raises:
            InputError: If the path cannot be resolved.
            ShExError: If the cache file is invalid.
        """
    def validate_shex(self) -> ShExValidationReport:
        r"""
        Validates the current RDF data against the loaded ShEx schema using the current ShapeMap.
        
        Returns:
            ShExValidationReport: A snapshot of the result — ``.conforms``,
            ``.violations``, ``len()`` and iteration. Unaffected by later calls on the
            session.
        
        Raises:
            ValidationError: If no schema, data, or ShapeMap is loaded.
        """
    def serialize_shex_validation_results(self, format: typing.Optional[ResultShexValidationFormat] = None, sort_mode: typing.Optional[ShexValidationSortMode] = None) -> builtins.str:
        r"""
        Serializes the results of the most recent :meth:`validate_shex` call.
        
        Args:
            format (ResultShexValidationFormat, optional): Output format. Defaults to
                ``ResultShexValidationFormat.Details``.
            sort_mode (ShexValidationSortMode, optional): Sorting mode. Defaults to
                ``ShexValidationSortMode.Node``.
        
        Returns:
            str: Serialized validation results.
        
        Raises:
            ValidationError: If there are no results to serialize.
        """
    def add_external_resolver(self, spec: builtins.str) -> None:
        r"""
        Registers an external-shape resolver from a spec string.
        
        The spec follows the grammar ``<kind>[:<arg>]``. Built-in kinds (see :meth:`list_external_resolvers`):
        * ``reject-all`` — reject any unhandled EXTERNAL shape.
        * ``schema:<path>`` — substitute EXTERNAL declarations using a ShEx file.
        
        Resolvers are prepended to the chain, so the most recently added is consulted
        first. Call this **before** :meth:`read_shex`, because the compiler reads the
        chain during AST-to-IR.
        
        Args:
            spec (str): Resolver spec string.
        
        Raises:
            ShExError: If the spec is malformed or the resolver cannot be built.
        """
    def clear_external_resolvers(self) -> None:
        r"""
        Resets the external-shape resolver chain to the default (``reject-all`` only).
        """
    @staticmethod
    def list_external_resolvers() -> builtins.list[tuple[builtins.str, builtins.str, builtins.str]]:
        r"""
        Returns the built-in external-shape resolver kinds.
        
        Returns:
            list[tuple[str, str, str]]: ``(name, description, spec_syntax)`` triples
            documenting the kinds accepted by :meth:`add_external_resolver`.
        """

@typing.final
class RudofConfig:
    def __new__(cls) -> RudofConfig: ...
    @staticmethod
    def from_path(path: builtins.str | os.PathLike | pathlib.Path) -> RudofConfig:
        r"""
        Loads a RudofConfig from a file path.
        """
    def __repr__(self) -> builtins.str: ...

class RudofError(builtins.Exception):
    r"""
    Base class for all errors raised by pyrudof.
    """
    ...

class ServiceError(RudofError):
    r"""
    A service description could not be read or written.
    """
    ...

class ShExError(RudofError):
    r"""
    A ShEx schema could not be parsed, compiled or serialized.
    """
    ...

@typing.final
class ShExValidationEntry:
    r"""
    One ``(node, shape, status)`` row of a ShEx validation result.
    """
    @property
    def node(self) -> builtins.str:
        r"""
        The focus node, as a string.
        """
    @property
    def shape(self) -> builtins.str:
        r"""
        The shape label it was checked against.
        """
    @property
    def status(self) -> builtins.str:
        r"""
        ``"conformant"``, ``"nonconformant"``, ``"pending"`` or ``"inconsistent"``.
        """
    @property
    def details(self) -> typing.Optional[builtins.str]:
        r"""
        The reason or appinfo carried by the status, if any.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ShExValidationEntryIterator:
    r"""
    Iterator over a :class:`ShExValidationReport`'s entries.
    """
    def __iter__(self) -> ShExValidationEntryIterator: ...
    def __next__(self) -> ShExValidationEntry: ...
    def __length_hint__(self) -> builtins.int: ...

@typing.final
class ShExValidationReport:
    r"""
    The result of the most recent :meth:`Rudof.validate_shex` call.
    """
    @property
    def conforms(self) -> builtins.bool:
        r"""
        ``True`` if every entry is conformant.
        
        An empty report is vacuously conformant; use ``len()`` to tell the two apart.
        """
    @property
    def violations(self) -> builtins.list[ShExValidationEntry]:
        r"""
        The entries that are **not** conformant.
        """
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> ShExValidationEntryIterator: ...
    def __bool__(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ShaclError(RudofError):
    r"""
    A SHACL shapes graph could not be parsed or serialized.
    """
    ...

@typing.final
class ShaclValidationEntry:
    r"""
    One violation of a SHACL validation report.
    """
    @property
    def focus_node(self) -> builtins.str:
        r"""
        The node that failed validation, as a string.
        """
    @property
    def path(self) -> typing.Optional[builtins.str]:
        r"""
        The property path the violation was found at, if any.
        """
    @property
    def value(self) -> typing.Optional[builtins.str]:
        r"""
        The value that caused the violation, if any.
        """
    @property
    def source_shape(self) -> typing.Optional[builtins.str]:
        r"""
        The shape that was violated, if any.
        """
    @property
    def constraint_component(self) -> builtins.str:
        r"""
        The SHACL constraint component that reported the violation.
        """
    @property
    def severity(self) -> builtins.str:
        r"""
        ``"Violation"``, ``"Warning"``, ``"Info"``, ``"Debug"``, ``"Trace"``, or the IRI
        of a custom severity.
        """
    @property
    def message(self) -> builtins.str:
        r"""
        The messages attached to the violation, joined by newlines. Empty when the shape
        declares no ``sh:message``.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ShaclValidationEntryIterator:
    r"""
    Iterator over a :class:`ShaclValidationReport`'s entries.
    """
    def __iter__(self) -> ShaclValidationEntryIterator: ...
    def __next__(self) -> ShaclValidationEntry: ...
    def __length_hint__(self) -> builtins.int: ...

@typing.final
class ShaclValidationReport:
    r"""
    The result of the most recent :meth:`Rudof.validate_shacl` call.
    
    A snapshot: it owns its data and is unaffected by later calls on the session.
    """
    @property
    def conforms(self) -> builtins.bool:
        r"""
        ``True`` if the data conforms to the shapes graph.
        
        Reported by the validator, not derived from the entries.
        """
    @property
    def violations(self) -> builtins.list[ShaclValidationEntry]:
        r"""
        Every violation in the report. Alias of iterating the report.
        """
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> ShaclValidationEntryIterator: ...
    def __bool__(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

class ShapeMapError(RudofError):
    r"""
    A ShapeMap could not be parsed or serialized.
    """
    ...

class UnsupportedOperationError(RudofError):
    r"""
    The requested operation is not implemented.
    """
    ...

class ValidationError(RudofError):
    r"""
    Validation itself failed (not: validation reported violations).
    """
    ...

@typing.final
class ArcDirection(enum.Enum):
    r"""
    Direction in which an arc is followed from the node being expanded.
    """
    Outgoing = ...
    r"""
    The node is the subject of the arc.
    """
    Incoming = ...
    r"""
    The node is the object of the arc.
    """

    def __new__(cls) -> ArcDirection: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ArcDirection]: ...

@typing.final
class CardinalityStrategy(enum.Enum):
    r"""
    How many relationships to generate when a constraint allows a range.
    """
    Minimum = ...
    r"""
    Always use the minimum cardinality.
    """
    Maximum = ...
    r"""
    Always use the maximum cardinality, within reasonable bounds.
    """
    Random = ...
    r"""
    Choose a random value within the allowed range.
    """
    Balanced = ...
    r"""
    Favour realistic distributions across the allowed range.
    """

    def __new__(cls) -> CardinalityStrategy: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[CardinalityStrategy]: ...

@typing.final
class ConversionFormat(enum.Enum):
    r"""
    Conversion input formats.
    """
    Csv = ...
    r"""
    CSV - comma-separated values.
    """
    ShExC = ...
    r"""
    ShExC - compact ShEx syntax.
    """
    ShExJ = ...
    r"""
    ShExJ - JSON representation of a ShEx schema.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    Xlsx = ...
    r"""
    Excel workbook (`.xlsx`).
    """

    def __new__(cls) -> ConversionFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ConversionFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ConversionFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ConversionMode(enum.Enum):
    r"""
    Conversion input modes - the kind of schema being converted from.
    """
    Shacl = ...
    r"""
    SHACL shapes graph.
    """
    ShEx = ...
    r"""
    ShEx schema.
    """
    Dctap = ...
    r"""
    DCTAP profile.
    """

    def __new__(cls) -> ConversionMode: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ConversionMode]: ...

@typing.final
class DCTapFormat(enum.Enum):
    r"""
    DCTAP input formats.
    """
    Csv = ...
    r"""
    CSV - comma-separated values.
    """
    Xlsx = ...
    r"""
    Excel workbook (`.xlsx`).
    """
    Xlsb = ...
    r"""
    Excel binary workbook (`.xlsb`).
    """
    Xlsm = ...
    r"""
    Excel macro-enabled workbook (`.xlsm`).
    """
    Xls = ...
    r"""
    Legacy Excel workbook (`.xls`).
    """

    def __new__(cls) -> DCTapFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[DCTapFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> DCTapFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class DataQuality(enum.Enum):
    r"""
    How realistic and complex the generated data should be.
    """
    Low = ...
    r"""
    Simple random data.
    """
    Medium = ...
    r"""
    Realistic patterns.
    """
    High = ...
    r"""
    Complex realistic data with correlations.
    """

    def __new__(cls) -> DataQuality: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[DataQuality]: ...

@typing.final
class DbEngine(enum.Enum):
    Lbug = ...
    r"""
    LadybugDB, a local embedded property graph database.
    """

    def __new__(cls) -> DbEngine: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[DbEngine]:
        r"""
        Every variant of this enum, in declaration order.
        """

@typing.final
class DdlDialect(enum.Enum):
    r"""
    Target dialect for the property graph DDL generated by `pg_db_ddl`.
    """
    Cypher = ...
    r"""
    Cypher-style DDL.
    """
    Gql = ...
    r"""
    ISO GQL-style graph type DDL.
    """

    def __new__(cls) -> DdlDialect: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[DdlDialect]: ...

@typing.final
class EntityDistribution(enum.Enum):
    r"""
    How entities are distributed across the shapes of a schema.
    """
    Equal = ...
    r"""
    Equal distribution across all shapes.
    """

    def __new__(cls) -> EntityDistribution: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[EntityDistribution]: ...

@typing.final
class OutputFormat(enum.Enum):
    r"""
    RDF serialization used for generated data.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    NTriples = ...
    r"""
    N-Triples - line-based RDF format with one triple per line.
    """

    def __new__(cls) -> OutputFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[OutputFormat]: ...

@typing.final
class PgSchemaFormat(enum.Enum):
    r"""
    Property graph schema formats.
    """
    PgSchemaC = ...
    r"""
    PgSchemaC - compact property graph schema syntax.
    """

    def __new__(cls) -> PgSchemaFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[PgSchemaFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> PgSchemaFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class QueryResultFormat(enum.Enum):
    r"""
    Output formats for SPARQL query results.
    """
    Internal = ...
    r"""
    Internal representation used for processing.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    NTriples = ...
    r"""
    N-Triples - line-based RDF format with one triple per line.
    """
    JsonLd = ...
    r"""
    JSON-LD - JSON serialization for Linked Data.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """
    RdfXml = ...
    r"""
    RDF/XML - XML-based RDF serialization.
    """
    Csv = ...
    r"""
    CSV - comma-separated values for spreadsheet tools.
    """
    Markdown = ...
    r"""
    Markdown - a table suitable for documentation.
    """
    TriG = ...
    r"""
    TriG - Turtle extended with named graphs.
    """
    N3 = ...
    r"""
    Notation3 - superset of Turtle.
    """
    NQuads = ...
    r"""
    N-Quads - N-Triples extended with named graphs.
    """

    def __new__(cls) -> QueryResultFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[QueryResultFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> QueryResultFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class QueryType(enum.Enum):
    r"""
    The kind of SPARQL query being run.
    """
    Select = ...
    r"""
    SELECT - returns a table of bindings.
    """
    Construct = ...
    r"""
    CONSTRUCT - returns an RDF graph.
    """
    Ask = ...
    r"""
    ASK - returns a boolean.
    """
    Describe = ...
    r"""
    DESCRIBE - returns an RDF graph describing the matched resources.
    """

    def __new__(cls) -> QueryType: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[QueryType]: ...

@typing.final
class RDFFormat(enum.Enum):
    r"""
    RDF data serialization formats supported when reading or writing graphs.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    NTriples = ...
    r"""
    N-Triples - line-based RDF format with one triple per line.
    """
    RdfXml = ...
    r"""
    RDF/XML - XML-based RDF serialization.
    """
    TriG = ...
    r"""
    TriG - Turtle extended with named graphs.
    """
    N3 = ...
    r"""
    Notation3 - superset of Turtle.
    """
    NQuads = ...
    r"""
    N-Quads - N-Triples extended with named graphs.
    """
    JsonLd = ...
    r"""
    JSON-LD - JSON serialization for Linked Data.
    """
    Pg = ...
    r"""
    Property Graph format - nodes and edges (non-RDF).
    """

    def __new__(cls) -> RDFFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[RDFFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> RDFFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class RdfConfigFormat(enum.Enum):
    r"""
    rdf-config input formats.
    """
    Yaml = ...
    r"""
    YAML - the rdf-config specification format.
    """

    def __new__(cls) -> RdfConfigFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[RdfConfigFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> RdfConfigFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ReaderMode(enum.Enum):
    r"""
    How strictly parsers react to malformed input.
    """
    Lax = ...
    r"""
    Ignore non-fatal errors and continue processing.
    """
    Strict = ...
    r"""
    Fail immediately on the first parsing error.
    """

    def __new__(cls) -> ReaderMode: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ReaderMode]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ReaderMode:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ResultConversionFormat(enum.Enum):
    r"""
    Conversion output formats.
    """
    Default = ...
    r"""
    The default format for the selected output mode.
    """
    Internal = ...
    r"""
    Internal representation used for processing.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """
    ShExC = ...
    r"""
    ShExC - compact ShEx syntax.
    """
    ShExJ = ...
    r"""
    ShExJ - JSON representation of a ShEx schema.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    PlantUML = ...
    r"""
    PlantUML - text-based UML diagram source.
    """
    Html = ...
    r"""
    HTML documentation.
    """
    Svg = ...
    r"""
    SVG - Scalable Vector Graphics image.
    """
    Png = ...
    r"""
    PNG - Portable Network Graphics image.
    """

    def __new__(cls) -> ResultConversionFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ResultConversionFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ResultConversionFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ResultConversionMode(enum.Enum):
    r"""
    Conversion output modes - the kind of artifact being converted to.
    """
    Sparql = ...
    r"""
    SPARQL queries.
    """
    ShEx = ...
    r"""
    ShEx schema.
    """
    Uml = ...
    r"""
    UML diagram.
    """
    Html = ...
    r"""
    HTML documentation.
    """
    Shacl = ...
    r"""
    SHACL shapes graph.
    """

    def __new__(cls) -> ResultConversionMode: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ResultConversionMode]: ...

@typing.final
class ResultDCTapFormat(enum.Enum):
    r"""
    DCTAP output formats.
    """
    Internal = ...
    r"""
    Internal representation used for processing.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """

    def __new__(cls) -> ResultDCTapFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ResultDCTapFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ResultDCTapFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ResultDataFormat(enum.Enum):
    r"""
    Output formats for serializing the currently loaded RDF data.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    NTriples = ...
    r"""
    N-Triples - line-based RDF format with one triple per line.
    """
    JsonLd = ...
    r"""
    JSON-LD - JSON serialization for Linked Data.
    """
    RdfXml = ...
    r"""
    RDF/XML - XML-based RDF serialization.
    """
    TriG = ...
    r"""
    TriG - Turtle extended with named graphs.
    """
    N3 = ...
    r"""
    Notation3 - superset of Turtle.
    """
    NQuads = ...
    r"""
    N-Quads - N-Triples extended with named graphs.
    """
    Compact = ...
    r"""
    Compact - concise textual summary of the graph.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """
    PlantUML = ...
    r"""
    PlantUML - text-based UML diagram source.
    """
    Svg = ...
    r"""
    SVG - Scalable Vector Graphics image.
    """
    Png = ...
    r"""
    PNG - Portable Network Graphics image.
    """

    def __new__(cls) -> ResultDataFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ResultDataFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ResultDataFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ResultPgSchemaValidationFormat(enum.Enum):
    r"""
    Output formats for property graph schema validation results.
    """
    Compact = ...
    r"""
    Compact - concise validation output.
    """
    Details = ...
    r"""
    Verbose output including validation details.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """
    Csv = ...
    r"""
    CSV - comma-separated values for spreadsheet tools.
    """

    def __new__(cls) -> ResultPgSchemaValidationFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ResultPgSchemaValidationFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ResultPgSchemaValidationFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ResultRdfConfigFormat(enum.Enum):
    r"""
    rdf-config output formats.
    """
    Internal = ...
    r"""
    Internal representation used for processing.
    """
    Yaml = ...
    r"""
    YAML - the rdf-config specification format.
    """

    def __new__(cls) -> ResultRdfConfigFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ResultRdfConfigFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ResultRdfConfigFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ResultShaclValidationFormat(enum.Enum):
    r"""
    Output formats for SHACL validation results.
    """
    Details = ...
    r"""
    Verbose output including validation details.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    NTriples = ...
    r"""
    N-Triples - line-based RDF format with one triple per line.
    """
    RdfXml = ...
    r"""
    RDF/XML - XML-based RDF serialization.
    """
    TriG = ...
    r"""
    TriG - Turtle extended with named graphs.
    """
    N3 = ...
    r"""
    Notation3 - superset of Turtle.
    """
    NQuads = ...
    r"""
    N-Quads - N-Triples extended with named graphs.
    """
    Minimal = ...
    r"""
    Minimal - the shortest possible validation report.
    """
    Compact = ...
    r"""
    Compact - concise validation output.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """
    Csv = ...
    r"""
    CSV - comma-separated values for spreadsheet tools.
    """

    def __new__(cls) -> ResultShaclValidationFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ResultShaclValidationFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ResultShaclValidationFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ResultShexValidationFormat(enum.Enum):
    r"""
    Output formats for ShEx validation results.
    """
    Details = ...
    r"""
    Verbose output including validation details.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    NTriples = ...
    r"""
    N-Triples - line-based RDF format with one triple per line.
    """
    RdfXml = ...
    r"""
    RDF/XML - XML-based RDF serialization.
    """
    TriG = ...
    r"""
    TriG - Turtle extended with named graphs.
    """
    N3 = ...
    r"""
    Notation3 - superset of Turtle.
    """
    NQuads = ...
    r"""
    N-Quads - N-Triples extended with named graphs.
    """
    Compact = ...
    r"""
    Compact - concise ShapeMap representation.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """
    Csv = ...
    r"""
    CSV - comma-separated values for spreadsheet tools.
    """

    def __new__(cls) -> ResultShexValidationFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ResultShexValidationFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ResultShexValidationFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class SchemaFormat(enum.Enum):
    r"""
    Schema language a generator input is written in.
    """
    ShEx = ...
    r"""
    ShEx (Shape Expressions).
    """
    Shacl = ...
    r"""
    SHACL (Shapes Constraint Language).
    """

    def __new__(cls) -> SchemaFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[SchemaFormat]: ...

@typing.final
class ServiceDescriptionFormat(enum.Enum):
    r"""
    Service description serialization formats.
    """
    Internal = ...
    r"""
    Internal representation used for processing.
    """
    Mie = ...
    r"""
    MIE - machine-readable interface description.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """

    def __new__(cls) -> ServiceDescriptionFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ServiceDescriptionFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ServiceDescriptionFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ShExFormat(enum.Enum):
    r"""
    ShEx schema serialization formats.
    """
    Internal = ...
    r"""
    Internal representation used for processing.
    """
    Simple = ...
    r"""
    Simplified ShEx representation.
    """
    ShExC = ...
    r"""
    ShExC - compact ShEx syntax (human-readable).
    """
    ShExJ = ...
    r"""
    ShExJ - JSON representation of a ShEx schema.
    """
    Json = ...
    r"""
    JSON - generic JSON format.
    """
    JsonLd = ...
    r"""
    JSON-LD - JSON serialization for Linked Data.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    NTriples = ...
    r"""
    N-Triples - line-based RDF format with one triple per line.
    """
    RdfXml = ...
    r"""
    RDF/XML - XML-based RDF serialization.
    """
    TriG = ...
    r"""
    TriG - Turtle extended with named graphs.
    """
    N3 = ...
    r"""
    Notation3 - superset of Turtle.
    """
    NQuads = ...
    r"""
    N-Quads - N-Triples extended with named graphs.
    """
    PlantUML = ...
    r"""
    PlantUML - text-based UML diagram source.
    """
    Svg = ...
    r"""
    SVG - Scalable Vector Graphics image.
    """
    Png = ...
    r"""
    PNG - Portable Network Graphics image.
    """
    Binary = ...
    r"""
    Binary - precompiled schema cache.
    """

    def __new__(cls) -> ShExFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ShExFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ShExFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ShaclFormat(enum.Enum):
    r"""
    SHACL shapes graph serialization formats.
    """
    Internal = ...
    r"""
    Internal representation used for processing.
    """
    Turtle = ...
    r"""
    Turtle - compact, human-readable RDF format.
    """
    NTriples = ...
    r"""
    N-Triples - line-based RDF format with one triple per line.
    """
    RdfXml = ...
    r"""
    RDF/XML - XML-based RDF serialization.
    """
    TriG = ...
    r"""
    TriG - Turtle extended with named graphs.
    """
    N3 = ...
    r"""
    Notation3 - superset of Turtle.
    """
    NQuads = ...
    r"""
    N-Quads - N-Triples extended with named graphs.
    """
    JsonLd = ...
    r"""
    JSON-LD - JSON serialization for Linked Data.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """

    def __new__(cls) -> ShaclFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ShaclFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ShaclFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ShaclValidationMode(enum.Enum):
    r"""
    SHACL validation engine.
    """
    Native = ...
    r"""
    Rust-native engine.
    """
    Sparql = ...
    r"""
    SPARQL-based engine, validating through SPARQL queries.
    """

    def __new__(cls) -> ShaclValidationMode: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ShaclValidationMode]: ...

@typing.final
class ShaclValidationSortMode(enum.Enum):
    r"""
    Sort mode for displaying a SHACL validation report as a table.
    """
    Severity = ...
    r"""
    Group results by violation severity.
    """
    Node = ...
    r"""
    Group results by the focus node being validated.
    """
    Component = ...
    r"""
    Group results by SHACL constraint component.
    """
    Value = ...
    r"""
    Group results by the value that caused the violation.
    """
    Path = ...
    r"""
    Group results by the property path where violations occur.
    """
    SourceShape = ...
    r"""
    Group results by the shape that was violated.
    """
    Details = ...
    r"""
    Group results by detailed information.
    """

    def __new__(cls) -> ShaclValidationSortMode: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ShaclValidationSortMode]: ...

@typing.final
class ShapeMapFormat(enum.Enum):
    r"""
    ShapeMap serialization formats.
    """
    Compact = ...
    r"""
    Compact - human-readable ShapeMap syntax.
    """
    Internal = ...
    r"""
    Internal representation used for processing.
    """
    Json = ...
    r"""
    JSON - machine-readable JSON serialization.
    """
    Details = ...
    r"""
    Details - verbose output including validation details.
    """
    Csv = ...
    r"""
    CSV - comma-separated values for spreadsheet tools.
    """

    def __new__(cls) -> ShapeMapFormat: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ShapeMapFormat]: ...
    @classmethod
    def from_str(cls, s: builtins.str) -> ShapeMapFormat:
        r"""
        Parses a variant from its name, case-insensitively.
        """

@typing.final
class ShapesGraphSource(enum.Enum):
    r"""
    Source of the SHACL shapes graph used during validation.
    
    Shapes can come from the current SHACL schema or be extracted from the current RDF
    data graph.
    """
    CurrentData = ...
    r"""
    Shapes come from the current RDF data graph.
    """
    CurrentSchema = ...
    r"""
    Shapes come from the current SHACL schema.
    """

    def __new__(cls) -> ShapesGraphSource: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ShapesGraphSource]:
        r"""
        Every variant of this enum, in declaration order.
        """

@typing.final
class ShexValidationSortMode(enum.Enum):
    r"""
    Sort mode for displaying a ShEx validation result as a table.
    """
    Node = ...
    r"""
    Sort rows by focus node.
    """
    Shape = ...
    r"""
    Sort rows by shape label.
    """
    Status = ...
    r"""
    Sort rows by validation status.
    """
    Details = ...
    r"""
    Sort rows by detailed information.
    """

    def __new__(cls) -> ShexValidationSortMode: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    @classmethod
    def all(cls) -> builtins.list[ShexValidationSortMode]: ...

