use pyo3::prelude::*;
use rudof_lib::formats::{BackendSpec, DdlDialect, PgSchemaFormat, ResultPgSchemaValidationFormat};

pyenum! {
    /// Property graph schema formats.
    "PgSchemaFormat": PyPgSchemaFormat => PgSchemaFormat, default = PgSchemaC, from_str {
        /// PgSchemaC - compact property graph schema syntax.
        PgSchemaC => PgSchemaC,
    }
}

pyenum! {
    /// Output formats for property graph schema validation results.
    "ResultPgSchemaValidationFormat": PyResultPgSchemaValidationFormat
        => ResultPgSchemaValidationFormat, default = Compact, from_str {
        /// Compact - concise validation output.
        Compact => Compact,
        /// Verbose output including validation details.
        Details => Details,
        /// JSON - machine-readable JSON serialization.
        Json    => Json,
        /// CSV - comma-separated values for spreadsheet tools.
        Csv     => Csv,
    }
}

pyenum! {
    /// Target dialect for the property graph DDL generated by `pg_db_ddl`.
    "DdlDialect": PyDdlDialect => DdlDialect, default = Cypher {
        /// Cypher-style DDL.
        Cypher => Cypher,
        /// ISO GQL-style graph type DDL.
        Gql    => Gql,
    }
}

#[cfg_attr(feature = "stub-gen", pyo3_stub_gen_derive::gen_stub_pyclass_enum)]
#[pyclass(
    eq,
    eq_int,
    hash,
    frozen,
    from_py_object,
    name = "DbEngine",
    module = "pyrudof._pyrudof"
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PyDbEngine {
    /// LadybugDB, a local embedded property graph database.
    Lbug,
}

impl From<&PyDbEngine> for BackendSpec {
    fn from(engine: &PyDbEngine) -> Self {
        match engine {
            PyDbEngine::Lbug => BackendSpec::Lbug,
        }
    }
}

impl From<PyDbEngine> for BackendSpec {
    fn from(engine: PyDbEngine) -> Self {
        (&engine).into()
    }
}

#[cfg_attr(feature = "stub-gen", pyo3_stub_gen_derive::gen_stub_pymethods)]
#[pymethods]
impl PyDbEngine {
    #[new]
    fn __init__() -> Self {
        PyDbEngine::Lbug
    }

    fn __str__(&self) -> String {
        match self {
            PyDbEngine::Lbug => "Lbug".to_string(),
        }
    }

    fn __repr__(&self) -> String {
        format!("DbEngine.{}", self.__str__())
    }

    /// Every variant of this enum, in declaration order.
    #[classmethod]
    fn all(_cls: &Bound<'_, pyo3::types::PyType>) -> Vec<PyDbEngine> {
        vec![PyDbEngine::Lbug]
    }
}

use rudof_lib::types::{PgSchemaResultAssociation, PgSchemaValidationResult};

/// One ``(node, type)`` association of a property graph schema validation result.
#[cfg_attr(feature = "stub-gen", pyo3_stub_gen_derive::gen_stub_pyclass)]
#[pyclass(
    frozen,
    get_all,
    from_py_object,
    name = "PgSchemaValidationEntry",
    module = "pyrudof._pyrudof"
)]
#[derive(Clone)]
pub struct PyPgSchemaValidationEntry {
    /// The identifier of the node that was checked.
    pub node_id: String,
    /// The name of the type it was checked against.
    pub type_name: String,
    /// ``True`` when the node conforms to the type.
    pub conforms: bool,
    /// The errors that made it fail, or the evidences that made it pass, joined by ``"; "``.
    pub details: String,
}

#[cfg_attr(feature = "stub-gen", pyo3_stub_gen_derive::gen_stub_pymethods)]
#[pymethods]
impl PyPgSchemaValidationEntry {
    fn __repr__(&self) -> String {
        format!(
            "PgSchemaValidationEntry(node_id='{}', type_name='{}', conforms={})",
            self.node_id,
            self.type_name,
            if self.conforms { "True" } else { "False" }
        )
    }
}

impl From<&PgSchemaResultAssociation> for PyPgSchemaValidationEntry {
    fn from(association: &PgSchemaResultAssociation) -> Self {
        let details = association
            .details
            .as_ref()
            .map_left(|errors| join_details(errors.iter().map(|e| e.to_string())))
            .map_right(|evidences| join_details(evidences.iter().map(|e| e.to_string())))
            .into_inner();
        PyPgSchemaValidationEntry {
            node_id: association.node_id.clone(),
            type_name: association.type_name.clone(),
            conforms: association.conforms,
            details,
        }
    }
}

fn join_details(parts: impl Iterator<Item = String>) -> String {
    parts.collect::<Vec<_>>().join("; ")
}

/// The result of the most recent :meth:`Rudof.validate_pgschema` call.
///
/// A snapshot: it owns its data and is unaffected by later calls on the session.
#[cfg_attr(feature = "stub-gen", pyo3_stub_gen_derive::gen_stub_pyclass)]
#[pyclass(frozen, name = "PgSchemaValidationReport", module = "pyrudof._pyrudof")]
pub struct PyPgSchemaValidationReport {
    // No `inner` here, unlike the ShEx and SHACL reports: `PgSchemaValidationResult`
    // derives only `Debug, Serialize`, so it cannot be cloned out of the session.
    pub(crate) conforms: bool,
    pub(crate) entries: Vec<PyPgSchemaValidationEntry>,
}

impl PyPgSchemaValidationReport {
    pub(crate) fn new(inner: &PgSchemaValidationResult) -> Self {
        Self {
            conforms: inner.is_valid,
            entries: inner.associations.iter().map(Into::into).collect(),
        }
    }
}

#[cfg_attr(feature = "stub-gen", pyo3_stub_gen_derive::gen_stub_pymethods)]
#[pymethods]
impl PyPgSchemaValidationReport {
    /// ``True`` if every association conforms.
    ///
    /// Reported by the validator, not derived from the entries.
    #[getter]
    fn conforms(&self) -> bool {
        self.conforms
    }

    /// The associations that do **not** conform.
    #[getter]
    fn violations(&self) -> Vec<PyPgSchemaValidationEntry> {
        self.entries.iter().filter(|e| !e.conforms).cloned().collect()
    }

    fn __len__(&self) -> usize {
        self.entries.len()
    }

    fn __iter__(slf: PyRef<'_, Self>) -> PyPgSchemaValidationEntries {
        PyPgSchemaValidationEntries {
            inner: slf.entries.clone().into_iter(),
        }
    }

    fn __bool__(&self) -> bool {
        self.conforms
    }

    fn __repr__(&self) -> String {
        format!(
            "PgSchemaValidationReport(conforms={}, entries={})",
            if self.conforms { "True" } else { "False" },
            self.entries.len()
        )
    }
}

/// Iterator over a :class:`PgSchemaValidationReport`'s entries.
#[cfg_attr(feature = "stub-gen", pyo3_stub_gen_derive::gen_stub_pyclass)]
#[pyclass(name = "PgSchemaValidationEntryIterator", module = "pyrudof._pyrudof")]
pub struct PyPgSchemaValidationEntries {
    inner: std::vec::IntoIter<PyPgSchemaValidationEntry>,
}

#[cfg_attr(feature = "stub-gen", pyo3_stub_gen_derive::gen_stub_pymethods)]
#[cfg_attr(not(feature = "stub-gen"), pyo3_stub_gen_derive::remove_gen_stub)]
#[pymethods]
impl PyPgSchemaValidationEntries {
    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {
        slf
    }

    // `None` is how pyo3 signals StopIteration; it is never yielded to Python, so
    // the stub must not widen the element type to `Entry | None`.
    #[gen_stub(override_return_type(type_repr = "PgSchemaValidationEntry"))]
    fn __next__(&mut self) -> Option<PyPgSchemaValidationEntry> {
        self.inner.next()
    }

    fn __length_hint__(&self) -> usize {
        self.inner.len()
    }
}
