name = "mardi"

query_url = "https://query.portal.mardi4nfdi.de/sparql"

[prefixmap]
wd = "https://portal.mardi4nfdi.de/entity/"
wdt = "https://portal.mardi4nfdi.de/prop/direct/"
schema = "http://schema.org/"
p = "https://portal.mardi4nfdi.de/prop/"
wbo = "http://wikiba.se/ontology#"
rdfs = "http://www.w3.org/2000/01/rdf-schema#"
skos = "http://www.w3.org/2004/02/skos/core#"
wds = "https://portal.mardi4nfdi.de/entity/statement/"
xsd = "http://www.w3.org/2001/XMLSchema#"
bd = "http://www.bigdata.com/rdf#"
cc = "http://creativecommons.org/ns#"
dct = "http://purl.org/dc/terms/"
geo = "http://www.opengis.net/ont/geosparql#"
hint = "http://www.bigdata.com/queryHints#"
ontolex = "http://www.w3.org/ns/lemon/ontolex#"
owl = "http://www.w3.org/2002/07/owl#"
prov = "http://www.w3.org/ns/prov#"
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
pq = "http://portal.mardi4nfdi.de/prop/qualifier/"
pqn = "http://portal.mardi4nfdi.de/prop/qualifier/value-normalized/"
pqv = "http://portal.mardi4nfdi.de/prop/qualifier/value/"
pr = "http://portal.mardi4nfdi.de/prop/reference/"
prn = "http://portal.mardi4nfdi.de/prop/reference/value-normalized/"
prv = "http://portal.mardi4nfdi.de/prop/reference/value/"
psv = "http://portal.mardi4nfdi.de/prop/statement/value/"
ps = "http://portal.mardi4nfdi.de/prop/statement/"
psn = "http://portal.mardi4nfdi.de/prop/statement/value-normalized/"
wdata = "http://portal.mardi4nfdi.de/wiki/Special:EntityData/"
wdno = "http://portal.mardi4nfdi.de/prop/novalue/"
wdref = "http://portal.mardi4nfdi.de/reference/"
wdtn = "http://portal.mardi4nfdi.de/prop/direct-normalized/"
wdv = "http://portal.mardi4nfdi.de/value/"
wikibase = "http://wikiba.se/ontology#"
es = "https://portal.mardi4nfdi.de/wiki/Special:EntitySchemaText/"
