# TogoID SPARQL endpoint
name = "togoid"

query_url = "https://rdfportal.org/primary/sparql"

[prefixmap]
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
rdfs = "http://www.w3.org/2000/01/rdf-schema#"
tio = "http://togoid.dbcls.jp/ontology#"
up = "http://purl.uniprot.org/uniprot/"
pdb = "http://rdf.wwpdb.org/pdb/"
