[book]
authors = ["Jose Emilio Labra Gayo", "Ángel Iglesias Préstamo"]
language = "en"
multilingual = false
src = "src"
title = "rudof"
site-url = "/docs/"

[output.html.print]
enable = false

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
no-section-label = true
preferred-dark-theme = "dark"
git-repository-url = "https://github.com/rudof-project/rudof"
git-repository-icon = "fa-github"
additional-css = ["theme/pagetoc.css", "theme/highlight.css"]
additional-js = [
    "turtle.js",
    "shexc.js",
    "sparql.js",
    "init_highlight_on_load.js", # This is required as the last one after the custom highlight files to restart highlight
    "theme/pagetoc.js", 
    "mermaid.min.js", 
    "mermaid-init.js"
    ]
