name: CI - Nix

on:
  push:
    paths:
      - "**/*.nix"
      - "flake.lock"
  pull_request:
    paths:
      - "**/*.nix"
      - "flake.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    name: Flake check (${{ matrix.target }})
    runs-on: ${{ matrix.vm }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64
            vm: ubuntu-latest
          - target: aarch64
            vm: ubuntu-24.04-arm
          - target: aarch64
            vm: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Enable KVM
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run flake checks
        run: nix flake check -L
      - name: Build default package
        run: nix build .# -L
