name: CI

on:
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - ".github/**"
      - "**/LICENSE*"
      - "**/README*"
      - "**/CHANGELOG*"
      - "**/.dockerignore"
      - "**/Dockerfile*"
      - "**/*.md"
      - .readthedocs.yml
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - ".github/**"
      - "**/LICENSE*"
      - "**/README*"
      - "**/CHANGELOG*"
      - "**/.dockerignore"
      - "**/Dockerfile*"
      - "**/*.md"
      - .readthedocs.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo check
        run: cargo check --workspace

  check-wasm:
    name: Check wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo check
        run: cargo check --workspace --target wasm32-unknown-unknown

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Clippy check
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo test
        run: cargo test --workspace

  wasm-test:
    name: Test Suite on Wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: Run cargo test
        env:
          CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER: wasm-bindgen-test-runner
        run: cargo test --workspace --target wasm32-unknown-unknown --lib --tests
